export const MAIN_BANNERS_FETCH = 'MAIN_BANNERS_FETCH';

export const TMDB_INITIATE_FETCH_MOVIES = 'TMDB_INITIATE_FETCH_MOVIES';
export const TMDB_FETCH_MOVIES = 'TMDB_FETCH_MOVIES';
export const TMDB_INITIATE_FETCH_GENRES = 'TMDB_INITIATE_FETCH_GENRES';
export const TMDB_FETCH_GENRES = 'TMDB_FETCH_GENRES';
export const TMDB_INITIATE_FETCH_MOVIE = 'TMDB_INITIATE_FETCH_MOVIE';
export const TMDB_FETCH_MOVIE = 'TMDB_FETCH_MOVIE';
export const TMDB_INITIATE_FETCH_SIMILAR = 'TMDB_INITIATE_FETCH_SIMILAR';
export const TMDB_FETCH_SIMILAR = 'TMDB_FETCH_SIMILAR';
